### ISSUE TITLE
Bug : Prodcut Page , SIngle data page not redirecting. 

### ISSUE THREAD

**Issue by Mr-Mayankraj** [04amanrajj/myntra-clone#2]
![image](https://github.com/user-attachments/assets/b453c464-5608-4bb4-acec-8b01c67f8183)

After clicking on Any Product newpage  should be redirect with the particuler item and data.

**Comment by 04amanrajj** [comment]
Insted of adding a new page I added a popup winodw that provide extra detailes
![Screenshot from 2024-09-22 19-46-44](https://github.com/user-attachments/assets/9cd39bee-751f-4091-8f8a-007f5c9ac481)
mobile view:
![4efad290-272e-4c0a-9e80-2b4a21c230d6](https://github.com/user-attachments/assets/d058d7bc-ae9e-4e23-82d5-5ec84820ebaa)
